language: node_js
node_js:
  - "node"

script:
  - npm run lint
  - npm test -- --coverage
  - npm run build
  - npm run build:storybook

deploy:
  - provider: pages
    github_token: $GH_TOKEN
    skip_cleanup: true
    keep_history: true
    local_dir: docs
    on:
      branch: master
      repo: mesteche/lib-ui
  # - provider: npm
  #   email: "$NPM_EMAIL"
  #   api_key: "$NPM_TOKEN"
  #   tag: next
  #   skip_cleanup: true
  #   keep_history: true
  #   on:
  #     branch: master
  #     repo: mesteche/lib-ui
